name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v2
        name: login no docker
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - uses: actions/checkout@v3
      - name: Build and push the Docker image
        run: |
          cd images
          docker build . --file Dockerfile --tag adonaicosta/pombo-web:latest
          docker push adonaicosta/pombo-web:latest
